### ISSUE TITLE
Breaks formatting on redactor textarea

### ISSUE THREAD

**Issue by nilsmielke** [Pipits/externallinks-filter#1]
Hey Hussain,
I added the filter and am try to use it on a redactor textarea with editor configs. It does add the rel attribute as desired. But it also messes up my formatting of the textarea. When I turn the first line into an `<h3>` the entire textarea gets marked up as an h3—only in the frontend, that is, in Perch Admin it still looks correct.
When I turn the filter off, the formatting behaves as expected.
I hope, that is an easy fix?
![Bildschirmfoto 2020-07-27 um 13 36 44](https://user-images.githubusercontent.com/8496033/88537668-42611680-d00e-11ea-9e59-6e1dd9494828.png)

**Comment by husseinalhammad** [comment]
Hi Nils,

Thanks for reporting this. I think I know what's causing the issue. Hopefully I'll have time over the next week to fix it.

**Comment by seoMattH** [comment]
`<perch:content id="blockTextArea" type="textarea" size="l autowidth" label="Verbiage" density="2" quality="30" sharpen="2" order="5" editor="redactor" editor-config="normal" filter="externallinks" linkstarget="_blank" linksrel="noopener" html="true" required="true" count="words" bucket="pagePics" />`

When I use the code above for a text area block your filter for one paragraph in the block everything works great.  However if I have multiple paragraphs in the same block.  It takes the ending </p> of the first paragraph and moves it to the bottom of the last paragraph so I get a </p></p>

**Comment by husseinalhammad** [comment]
Hi @nilsmielke, [v1.0.2](https://github.com/Pipits/externallinks-filter/releases/tag/v1.0.2) is available now and should fix the issues you're experiencing.

**Comment by nilsmielke** [comment]
It does! Many thanks, @husseinalhammad.
