### ISSUE TITLE
Weird Paragraph Behavior

### ISSUE THREAD

**Issue by seoMattH** [Pipits/externallinks-filter#2]
Hussein,

<perch:content id="blockTextArea" type="textarea" size="l autowidth" label="Verbiage" density="2" quality="30" sharpen="2" order="5" editor="redactor" editor-config="normal" filter="externallinks" linkstarget="_blank" linksrel="noopener" html="true" required="true" count="words" bucket="pagePics" />

When I use the code above for a text area block your filter for one paragraph in the block everything works great. However if I have multiple paragraphs in the same block. It takes the ending </p> of the first paragraph and moves it to the bottom of the last paragraph so I get a </p></p> Here is an example on this page if you want to view the source https://nesheimswaterrestoration.com/water-damage

**Comment by husseinalhammad** [comment]
Hi @seoMattH I think the new update in [v1.0.2](https://github.com/Pipits/externallinks-filter/releases/tag/v1.0.2) should fix your issue.

**Comment by seoMattH** [comment]
That appears to have fixed it.  Thank you sir
